# 연습문제 (2) - 2 - 추가내용

In [16]:
import pandas as pd
# 주성분 분석용 패키지
from sklearn.decomposition import PCA
# 주성분 분석 결과를 DataFrame으로 확인할 수 있는 기능을 제공하는 패키지
from pca import pca 
# 표준화 처리 패키지
from sklearn.preprocessing import StandardScaler

from pandas import read_excel, DataFrame

from matplotlib import pyplot as plt
import seaborn as sb

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.getcwd())))
from helper import my_ols ,scailing,get_best_feature,setCategory

## 문제2

다음의 데이터 뉴욕 멘하튼의 주택임대료에 영향을 준다고 예상되는 변수들과 주택 임대료를 정리한 것이다.

다양한 변수 중에서 목표로 하는 종속변수는 rent이다. 분석하라

In [17]:
df = pd.read_excel("https://data.hossam.kr/E04/manhattan.xlsx")
df

,rent,bedrooms,bathrooms,size_sqft,min_to_subway,floor,building_age_yrs,no_fee,has_roofdeck,has_washer_dryer,has_doorman,has_elevator,has_dishwasher,has_patio,has_gym,neighborhood,borough
0,2550,0.0,1,480,9,2.0,17,1,1,0,0,1,1,0,1,Upper East Side,Manhattan
1,11500,2.0,2,2000,4,1.0,96,0,0,0,0,0,0,0,0,Greenwich Village,Manhattan
2,4500,1.0,1,916,2,51.0,29,0,1,0,1,1,1,0,0,Midtown,Manhattan
3,4795,1.0,1,975,3,8.0,31,0,0,0,1,1,1,0,1,Greenwich Village,Manhattan
4,17500,2.0,2,4800,3,4.0,136,0,0,0,1,1,1,0,1,Soho,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3534,4210,1.0,1,532,3,8.0,16,1,1,1,1,1,1,0,1,Chelsea,Manhattan
3535,6675,2.0,2,988,5,10.0,9,1,1,1,1,1,1,0,1,Tribeca,Manhattan
3536,1699,0.0,1,250,2,5.0,96,0,0,0,0,0,0,0,0,Little Italy,Manhattan
3537,3475,1.0,1,651,6,5.0,14,1,0,1,1,1,1,0,1,Midtown West,Manhattan
3538,4500,1.0,1,816,4,11.0,9,0,1,1,1,1,0,1,1,Tribeca,Manhattan

In [18]:
df2 = df.drop('borough', axis=1)
df3 = setCategory(df2, 'neighborhood')
df3.value_counts('neighborhood')

neighborhood
29    579
28    500
19    460
21    314
8     268
4     182
9     132
27    119
18    119
7     108
1     104
20     85
2      82
32     67
11     66
10     61
25     58
30     54
16     41
6      41
3      23
12     16
22     13
13     12
23      9
5       8
24      5
15      4
26      3
14      3
31      2
17      1
Name: count, dtype: int64

#### 표준화 진행

In [21]:
x_train_std_df, y_train_std_df = scailing(df3, 'rent')

In [23]:

x_train_std_df.head()

,bedrooms,bathrooms,size_sqft,min_to_subway,floor,building_age_yrs,no_fee,has_roofdeck,has_washer_dryer,has_doorman,has_elevator,has_dishwasher,has_patio,has_gym,neighborhood
0,-1.397410,-0.611790,-0.962011,0.730862,-0.904097,-0.888763,1.21585,2.336243,-0.436784,-0.625393,1.546964,2.094423,-0.241482,2.171931,0.962835
1,0.669863,1.056257,2.218694,-0.176116,-0.995343,1.117593,-0.82247,-0.428038,-0.436784,-0.625393,-0.646428,-0.477459,-0.241482,-0.460420,-0.844730
2,-0.363774,-0.611790,-0.049651,-0.538908,3.566974,-0.584000,-0.82247,2.336243,-0.436784,1.598995,1.546964,2.094423,-0.241482,-0.460420,-0.100439
3,-0.363774,-0.611790,0.073811,-0.357512,-0.356619,-0.533206,-0.82247,-0.428038,-0.436784,1.598995,1.546964,2.094423,-0.241482,2.171931,-0.844730
4,0.669863,1.056257,8.077886,-0.357512,-0.721604,2.133470,-0.82247,-0.428038,-0.436784,1.598995,1.546964,2.094423,-0.241482,2.171931,0.643853

### PCA 패키지를 사용한 분석

In [25]:
feature, topfeat_df = get_best_feature(x_train_std_df)
feature

[pca] >Extracting column labels from dataframe.
[pca] >Extracting row labels from dataframe.
[pca] >The PCA reduction is performed to capture [95.0%] explained variance using the [15] columns of the input data.
[pca] >Fit using PCA.
[pca] >Compute loadings and PCs.
[pca] >Compute explained variance.
[pca] >Number of components is [12] that covers the [95.00%] explained variance.
[pca] >The PCA reduction is performed on the [15] columns of the input dataframe.
[pca] >Fit using PCA.
[pca] >Compute loadings and PCs.
[pca] >Outlier detection using Hotelling T2 test with alpha=[0.05] and n_components=[12]
[pca] >Multiple test correction applied for Hotelling T2 test: [fdr_bh]
[pca] >Outlier detection using SPE/DmodX with n_std=[3]

['has_patio',
 'has_elevator',
 'neighborhood',
 'size_sqft',
 'no_fee',
 'has_dishwasher',
 'has_gym',
 'has_roofdeck',
 'min_to_subway',
 'building_age_yrs']

In [27]:
mdf = pd.merge(x_train_std_df, y_train_std_df, left_index=True, right_index=True)
ols_result = my_ols(mdf, y='rent', x=feature)
ols_result.summary

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   rent   R-squared:                       0.757
Model:                            OLS   Adj. R-squared:                  0.756
Method:                 Least Squares   F-statistic:                     1098.
Date:                Thu, 27 Jul 2023   Prob (F-statistic):               0.00
Time:                        13:30:26   Log-Likelihood:                -2519.3
No. Observations:                3539   AIC:                             5061.
Df Residuals:                    3528   BIC:                             5129.
Df Model:                          10
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept        -9.346e-17      0.008  -1.13e-14      1.000      -0.016       0.016
has_patio            0.0015      0.008      0.179      0.858      -0.015       0.018
has_elevator         0.0036      0.012      0.308      0.758      -0.019       0.026
neighborhood         0.0008      0.008      0.100      0.921      -0.016       0.017
size_sqft            0.8593      0.008    101.882      0.000       0.843       0.876
no_fee              -0.0095      0.009     -1.087      0.277      -0.027       0.008
has_dishwasher       0.0008      0.009      0.087      0.931      -0.017       0.019
has_gym          -1.995e-05      0.012     -0.002      0.999      -0.023       0.023
has_roofdeck         0.0040      0.010      0.383      0.701      -0.016       0.024
min_to_subway       -0.0252      0.008     -2.970      0.003      -0.042      -0.009
building_age_yrs    -0.1477      0.009    -16.951      0.000      -0.165      -0.131
==============================================================================
Omnibus:                      885.489   Durbin-Watson:                   2.058
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            11063.662
Skew:                           0.831   Prob(JB):                         0.00
Kurtosis:                      11.501   Cond. No.                         2.71
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""